### ISSUE TITLE
[Feature] Group Maker v2 Improvements

### ISSUE THREAD

**Issue by Gear61** [Gear61/Random-Name-Picker#121]
Each one of these should be its own pull request. These are arranged in order of priority.

1. Automatically fill in the number of groups field with the lowest number necessary to use up all the names when the user types into the number of names per group field.
2. Same as #1 but in reverse (# of groups -> # of names).
3. Show a "You have no names in the list to make groups with." error message if they try to make groups with an empty list.
4. Show a red warning on the settings dialog dynamically if the current settings are too much (e.g. asking for 5 groups of 2 with a name list of 9 people).
5. Show a warning on the settings dialog dynamically if the current settings will lead to uneven groups (same example as above, we will need to create a dangling group of 1).
6. Add a text to speech feature to read all the selected groups out loud. We can add a speech button to the toolbar (there should be a microphone icon). Use TextToSpeechManager for this.
7. Add a "Groups generated." confirmation message when the user successfully makes groups. It's possible that 2 iterations of groups are exactly the same (but the app did do something).
8. Add an "Automatically speak results" option to the group making settings dialog.

**Comment by mohammedhemaid** [comment]
The features that I suggest to make:

1. If the # of groups or  # of names is empty or zero the OK button will be disabled.
2. The default grouping will be 2 names per group and the # of groups should be related to the numberOfNamesInTheList so it will cover all the names.

**Comment by Gear61** [comment]
1. I agree with that. However, let's prevent that from happening as much as possible with intelligent auto-fill when the user fills in 1 field.
2. Sure

**Comment by Gear61** [comment]
Gonna break this up into smaller issues.
