### ISSUE TITLE
Combine Lists?

### ISSUE THREAD

**Issue by JZharay** [Gear61/Random-Name-Picker#128]
I swear at one point I was able to combine lists. In fact, I still have a combined list from two lists that are both 30 names each with the combined list being 60 long (which would of been a pain to do!). Thing is, I cannot figure out if you had it removed or if that was just a fluke at some point during your updates. I remember it being done through what is now your improved import feature, so maybe it was a fluke?

Either way, I humbly request a way to combine lists already made. I guess you could add the gear icon to the edit menu to then combine the lists from there.

**Comment by Gear61** [comment]
@JZharay I removed that feature as part of a refactor. I'll try to add it back soon!

**Comment by Gear61** [comment]
@JZharay It took a lot of tricky code, but the feature's back! Closing this out.
