### ISSUE TITLE
Alternate Uses: Oblique Strategies (creativity generator)

### ISSUE THREAD

**Issue by BradKML** [Gear61/Random-Name-Picker#184]
Oblique Strategies is a deck of cards that are made to inspire people
https://www.wikiwand.com/en/Oblique_Strategies
And I have compiled a list here for use in the Random Name Picker.
https://github.com/BrandonKMLee/vscode-oblique-strategies/tree/master/src/resources

**Comment by Gear61** [comment]
Sorry but this feels out of scope? This app is built to be generic.

**Comment by BradKML** [comment]
@Gear61 setting this as a default? (Or import lists through files if that is not possible)
Other than that it would also be useful to import lists from https://www.fantasynamegenerators.com/ and such?
