### ISSUE TITLE
[Feature] Group maker v1

### ISSUE THREAD

**Issue by Gear61** [Gear61/Random-Name-Picker#28]
Our current UI effectively only allows you to make 1 group at once. The inspiring use case here is teachers who are splitting up their class into teams for a group project.

Collaboration Model:
- We shouldn't merge these changes onto master, since master should represent what's in production and we want to break up the implementation of this (reviewing a 1,000 line pull request is not fun)
- On your fork, creating a group-maker branch. You will submit pull requests from that branch into the group-maker branch on the core repository
- Let's not do this feature all at once; it will make reviewing the pull requests and cleaning up the code very difficult. Let's break it up into small requests. I'm thinking an order like this:

1. Add the new tab
2. Add the empty state message and button
3. Add the settings dialog
4. Add the choosing logic. It will be a utility method that takes in a list of names (flat) and returns a list of lists of names (nested since it's a list of groups). We will not show the result in a list yet; just print it within a Toast and you can record that.
5. Set up the adapter with the cards and show the chosen list of groups

For v1:
- Choosing a single thing is still the most common use case. Choose should still be the first tab. Choose -> Groups -> Edit
- Similar to choose, there will be settings icon at the top that opens a settings dialog. In the beginning, it will only have 2 parameters. The number of people in each group and how many groups are desired. By default, the page should create 1 group of 2. If the user enters in 0 for some reason (this will make the feature do nothing), change it to 1 similar to the "Choose" page to protect themselves from their stupidity.
- Similar to the "Choose" page, we will anchor a "Make Groups" button to the bottom
- The empty state of the group page will be an instructional message saying "Use the {ion-android-settings} icon to customize your groups and then tap "Make Groups" at the bottom"
- When the groups are generated, we replace the empty state with a list of cards. Each card will say "Group #X and then have a new-line separated list of names in the group".

For v2 and beyond:
- Show a warning on the settings dialog dynamically if the current settings are too much (e.g. asking for 5 groups of 2 with a name list of 9 people)
- Show a warning on the settings dialog dynamically if the current settings will lead to uneven groups (same example as above, we will need to create a dangling group of 1)
- Add a text to speech feature to read all the selected groups out loud
- Allow certain names not to be paired with each other (maybe 2 students hate each other)

**Comment by mohammedhemaid** [comment]
@Gear61 For the Setting dialog, The "how many groups are desired", Should I make it as a Spinner or just a simple EditText. if it EditText, if I want to make a groups for all the names what number should I put?

**Comment by Gear61** [comment]
@mohammedhemaid Good question! Definitely don't use a spinner IMHO; that won't scale with large lists. If you use an EditText, prefill the text with 1 group as mentioned in the issue description.
