### ISSUE TITLE
[Refactor] Extract out edit and delete dialogs from the homepage adapter

### ISSUE THREAD

**Issue by Gear61** [Gear61/Random-Name-Picker#61]
This violates single responsibility design and makes the homepage adapter class confusing. We should make the dialogs into separate classes (EditListNameDialog and DeleteListDialog) that the activity instantiates and hooks together with the adapter detecting an icon click.

Details:
1. The dialogs shouldn't do any data mutation; it should only be responsible for UI. Let the activity mutate the database and shared preferences accordingly.
2. We will need to expose new methods in the homepage adapter to edit and delete items and refresh the list. The tricky part is figuring out how we can mutate the item (which item in the list do we change). Since all list names are unique, we can probably just use indexOf() and go from there (O(n) time is pretty cheap).
3. With this refactor, the homepage adapter shouldn't need to take in a Context anymore.

**Comment by mohammedhemaid** [comment]
I didn't depend on the name of the item to change the list, I passed the position through the methods and that make it O(1) time.
