### ISSUE TITLE
[Feature] Import from .csv files

### ISSUE THREAD

**Issue by Gear61** [Gear61/Random-Name-Picker#75]
Each column is another part of the name. So if the first column is "Alex" and the second column is "Chiou", you will create "Alex Chiou".

1. Add this feature as the bottom option in the bottom sheet.
2. This is a premium feature. If the user doesn't have premium, the title of the feature should be "[PREMIUM] Import from .csv file". Otherwise, it should just be "Import from .csv file".
3. Use this library for .csv parsing: https://github.com/osiegmar/FastCSV. I tried doing .csv parsing without a library and it's just too complicated. This library has worked out well for me in another app already.
4. For a .csv code sample, check out: https://github.com/Gear61/Simple-Flashcards. That library has a crash on API 24 and below out of the box, so we need to work our way around it. My other code already does that.
5. Similar to the import from .txt feature, we should open a page where the user can confirm what list we're going to create from the import.
6. Use the Storage Access Framework (SAF) to pull in the file, similar to the import from .txt feature: https://developer.android.com/guide/topics/providers/document-provider#open-client. This API is incredibly powerful and gives us access to far more than just the user's phone storage.
7. If the .csv file is very large, you may have UI stutters if you do everything on the UI thread. Keep that in mind.
8. To create a giant .csv, you can use the app! Create a list and duplicate a name many, many times. And then export it as a .csv file!

This is a pretty large feature and will take up >500 lines of code. Let's break it up across multiple pull requests, similar to what we did before. We can create an import-from-csv branch and slowly merge code in there. An idea of steps:
1. Add the option to bottom sheet where it will morph based on having premium/not having it
2. Add the code to open SAF and only choose from .csv files when user taps on the option.
3. When the user chooses a .csv file, open a basic activity
4. Parse the file name as the list name
5. Parse the file contents into a list of names
6. When user hits save, list is actually saved to database. Make sure the homepage is updated.

**Comment by mohammedhemaid** [comment]
Thank you for the explanation! 
I will start working on it ASAP.

I've tried the Simple Flashcard Plus and tried to import .xlsx and .xls format didn't work, also I like the way you disabled the other files format.

I was thinking to use this library: 
https://github.com/andruhon/android5xlsx 
https://github.com/andruhon/AndroidReadXLSX
But it needs to enable the MutliDex and that will affect the performance and it will increase the app size, I remember it will add 5MB Extra :( 👎  so I believe we should skip it for now.

**Comment by Gear61** [comment]
@mohammedhemaid Oh god, if something is going to add 5MB, it is definitely not worth it. Does .xlxs and .xls share the same file format as .csv?

Anyways, that would be a nice follow-up, especially if there's demand for it. I'm starting from .csv since it's the more commonly requested one.

**Comment by mohammedhemaid** [comment]
@Gear61 No it doesn't support .csv :(
