### ISSUE TITLE
[Bug] Name doesn't added to choose activity in the first add

### ISSUE THREAD

**Issue by mohammedhemaid** [Gear61/Random-Name-Picker#76]
This happens with me in some cases in the first time and some of them after making some changes:
https://photos.app.goo.gl/HCsrDgUjxfw3nrWq7

**Comment by Gear61** [comment]
Yeah, that bug has unfortunately been there for a while. I introduced it while adding a new feature in an irresponsible way a long time ago. But the good new is I have just fixed it! :)

Try updating your fork's master against that of the main repo and try again!

**Comment by mohammedhemaid** [comment]
Yes, It fixed sorry for the hurry

**Comment by Gear61** [comment]
No worries @mohammedhemaid! Thank you for reporting the bug! I would rather have too much signal than too little signal.
