### ISSUE TITLE
Prefill change name dialog with the current name

### ISSUE THREAD

**Issue by Gear61** [Gear61/Random-Name-Picker#84]
This is actually a complaint from one of the most popular negative reviews of the app, so this is a good enhancement to add. I almost consider it a bug fix (I usually do this for my apps, but I wrote this code a long time ago). A common use-case for renaming is that the user had a typo and entered in the name wrong.

Some notes:
- This is for the name changing dialog for names within a list, not the lists themselves.
- There are 2 name changing flows. If there is only 1 instance of a name, the name changing dialog shows automatically. If there's more than 1, we ask the user how many instances of the name they want to change and then open the name changing dialog. Let's make sure both of these flows work with our change.

Once we're done with this task, we can move on to a trickier one.

**Comment by Gear61** [comment]
@ALAA999 Feel free to ping me on Slack if you need any clarification/help on this in general!

**Comment by Gear61** [comment]
@ALAA999 Just rolled this out to 64,000 users! Thanks!

**Comment by alaaalzibda** [comment]
Glad to hear that! :)
